#!/bin/zsh




# set -e
# set -x

greetfunc()
{
    echo "Hello, Erle"
    #echo $?
    false
    if [ $? = 0 ]
        then echo "Success happens"
        else echo "Other stuff..."
    fi
    echo "The last command failed"
    false
    #echo "Fail again!"
}

testOutfunc()
{
    echo "How will I be named?"
    # false
    echo "...if I get this far?"

}


greetfunc
testOutfunc